spring:
  data:
    mongodb:
      uri: mongodb://yinnohs:123@localhost:27017/review-read?authSource=admin&authMechanism=SCRAM-SHA-1
  application:
    name: reviewRead
  cloud:
    config:
      enabled: false
      import-check: false

server:
  port: 5152

grpc:
  server:
    port: 5252
    address: 0.0.0.0
    max-inbound-message-size: 10MB
    max-inbound-stream-message-size: 10MB
    max-inbound-headers-per-stream: 1000
    max-concurrent-streams: 1000
    enable-reflection: true
