spring:
  application:
  name: review-auth-service
  port: 5433
  datasource:
    url: jdbc:postgresql://localhost:5433/review-auth
    username: yinnohs
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/changelog.yml
    contexts: development, production
    default-schema: public
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 5155
  jpa:
    hibernate:
      ddl-auto: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

jwt:
  auth:
    expiration: 1800000
  refresh:
    expiration: 604800000

rsa:
  private-key: classpath:certs/private-final-key.pem
  public-key: classpath:certs/public-key.pem


argon2:
  memory: 7168
  iterations: 5
  parallelism: 1
  saltLength: 2

