spring:
  application:
    name: reviewWrite
  datasource:
    url: jdbc:postgresql://localhost:5050/review-write
    username: yinnohs
    password: 123
    driver-class-name: org.postgresql.Driver
  cloud:
    config:
      enabled: false
      import-check: false

server:
  port: 5153

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect