spring:
  # Data source configuration for MongoDB
  data:
    mongodb:
      uri: ${MONGO_URI}

# Application name and cloud configuration
  application:
    name: reviewProcessor
  cloud:
    config:
      enabled: false
      import-check: false

# Kafka configuration for consuming messages
  kafka:
    bootstrap-servers: localhost:29092
    properties:
      schema.registry.url: http://localhost:8081
    consumer:
      group-id: review-processor-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        # Set specific.avro.reader to false or remove it (default is false)
        specific.avro.reader: false
# Server configuration
server:
  port: 5154
